version: '2'
services:
    amorrecords-app:
        image: amorrecords
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://amorrecords-postgresql:5432/amorrecords
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    amorrecords-postgresql:
        extends:
            file: postgresql.yml
            service: amorrecords-postgresql
